select * from customer;

-- 1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as 'total revenue' from customer
group by gender;

-- 2. Which customer used a discount but still spent more than the average purchase amount?  
select customer_id, purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- 3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as AvgRating from customer
-- where review_rating > (select avg(review_rating) from customer)
-- group by item_purchased; 
group by item_purchased
order by AvgRatin desc
limit 5;

-- 4. Compare the average purchase amounts standard and express shipping.
select shipping_type, round(avg(purchase_amount),2) as AvgPurchaseAmount from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type
order by AvgPurchaseAmount desc;

-- 5. Do Subscribed customers spend more? compare average spend and 
-- total revenue between subscribers and non-subscribers
 select 
	case when subscription_status = 'Yes' then 'subscriber' else 'non-subscriber' end as subscriptionStatus, 
	count(*) as TotalCustomer, 
	sum(purchase_amount) as totalrevenue, 
	avg(purchase_amount) as AvgPurchaseAmount 
from customer
group by subscriptionStatus;

-- 6. Which 5 products have the highest percentage of purchase with discount applied?
select item_purchased, 
	round(100* sum(case when discount_applied='Yes' then 1 else 0 end)/count(2), 2) as percentage_with_discount
    from customer
    group by item_purchased
    order by percentage_with_discount desc
    limit 5;
    
-- 7. Segments customers into New, Returning and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with customer_type as (
	select case 
		when previous_purchases = 1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
        else 'Loyal' end as Customer_segment
	from customer
)
select Customer_segment, count(*) from customer_type
group by Customer_segment;

-- 8. What are the top 3 most purchased products within each category?
with item_counts as (
select category, item_purchased, count(customer_id) as TotalOrders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, TotalOrders from item_counts
where item_rank <=3;

-- 9. Are customers who are repeat buyers (more than 20 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as totalcustomer from customer
where previous_purchases > 20
group by subscription_status
order by totalcustomer desc;

-- 10. What is the revenue contribution of each age group ?
select age_group, sum(purchase_amount) as totalrevenue from customer
group by age_group
order by totalrevenue;
 